### ISSUE TITLE
Making AUR Package, please let me know if  you want to add anything :D

### ISSUE THREAD

**Issue by dacadla** [elliot40404/ssm#1]
Love this because it lets me organize my kubernetes nodes easily! But sadly it's not available on the AUR so I will be working on that.

**Comment by dacadla** [comment]
Following these guidelines https://wiki.archlinux.org/title/Go_package_guidelines

**Comment by elliot40404** [comment]
Glad it was of help to you. I am just waiting for a little more traction before I start working on publishing for different packages managers
